name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Only run in tags

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3.0.0

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Build project with Pyinstaller
      run: make build

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}

    - name: Commit CHANGELOG
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md

    - name: Archive build output
      run: |
        cd dist
        zip -r swing_tool_gui.zip swing_tool_gui.app


    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.0.8
      with:
        body_path: CHANGELOG.md
        files: |
          dist/swing_tool_gui.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
